{*
 * @version    $Id: template.phtml 2 2009-07-13 20:58:52Z david@grudl.com $
 * @param Paginator $paginator
 * @param array     $steps
 *}

{if $paginator->pageCount > 1}
	<ul class="pagination pagination-sm">
<!--		<li class="{if $paginator->isFirst()}disabled{/if}">-->
<!--			<a href="{plink this, (expand) $params, page => $paginator->page - 1}">« Předchozí</a>-->
<!--		</li>-->
	  
	  	{foreach $steps as $step}
	  		<li class="{if $step == $paginator->page}active{/if}">
	  			<a href="{plink this, (expand) $params, page => $step}">{$step}</a>
	  		</li>
	  				
			{*if $iterator->nextValue > $step + 1}<span>…</span>{/if*}
		{/foreach}
		  
<!--		<li class="{if $paginator->isLast()}disabled{/if}">-->
<!--			<a href="{plink this, (expand) $params, page => $paginator->page + 1}">Další »</a>-->
<!--		</li>-->
	</ul>
{/if}